data:
  dataset: "sybil"
  datacache: "nlst"
  batch_size: 3
  val_split: 0.2
  date_format: "%Y"
  label: 'cancer_year1'
  cancer_year: 1

logging:
  log_every_n_steps: 4
  val_every_n_epoch: 1

model:
  model_name: "sybil"
  lmodel: "BinaryClassifier"
  noduleft_dim: 128
  checkpoint: null

optimization:
  lr: !!float 1e-5
  warmup_steps: 100
  epochs: 10000
  patience: 200

