data:
  dataset: "tdvit"
  datacache: "nlst"
  batch_size: 1000
  val_split: 0.2
  date_format: "%Y"
  label: 'lung_cancer'

logging:
  log_every_n_steps: 1
  val_every_n_epoch: 1

model:
  output_logit: True
  model_name: "tevit_masked"
  lmodel: "BinaryClassifier"
  noduleft_dim: 128
  y_one_hot: True
  checkpoint: null

optimization:
  lr: !!float 1e-5
  warmup_steps: 100
  epochs: 10000
  patience: 2000
  val_metric: "val_auc"

